- description: This test mainly focuses on reasoning-depth. It requires the LLM to understand the whole piece of code and infer that the second "result" is a typo that should be changed to "flights" because "flights" is used in later sentences. 
  threshold: 0.5
  vars: 
    name: 003_context_code_fix
    difficulties:
      context-length: 1
      reasoning-depth: 2
      instruction-compliance: 1
    prompt: file://testcases/003_context_code_fix_prompt.txt
  assert:
    - type: contains-any
      value: 
        - "const flights = result.data.data.map(flight => {"
        - "const result = response.data.data.map(flight => {"
        - "const result = flights.data.data.map(flight => {"
        - "const flightResults = result.data.data.map(flight => {"
      weight: 1
    - type: contains
      value: "const flights = result.data.data.map(flight => {"
      weight: 1