- description: This test mainly focuses on reasoning-depth. It tests the LLM's calculation and reasoning, and requires understanding the existence of leap years.
  threshold: 0.8
  vars: 
    name: 007_birthday_paradox
    difficulties:
      context-length: 1
      reasoning-depth: 2
      instruction-compliance: 1
    prompt: file://testcases/007_birthday_paradox_prompt.txt
  assert:
    - type: contains
      value: "23"
      weight: 4
    - type: contains
      value: "leep year"
      weight: 1  