- description: This test mainly focuses on reasoning-depth. It requires the LLM has the common sense that ball should fall out of the cup when the cup is reversed. 
  threshold: 0.6
  vars: 
    name: 007_find_ball
    difficulties:
      context-length: 1
      reasoning-depth: 2
      instruction-compliance: 1
    prompt: file://007_find_ball_prompt.txt
  assert:
    - type: javascript
      value: |
        var lowerCaseStr = output.toLowerCase();
        const bedroomIndex = lowerCaseStr.lastIndexOf("bedroom");
        const gardenIndex = lowerCaseStr.lastIndexOf("garden");
        const garageIndex = lowerCaseStr.lastIndexOf("garage");

        if (bedroomIndex > gardenIndex && bedroomIndex > garageIndex) {
            return 1;
        }
        return 0;
