- description: This test mainly focuses on reasoning-depth and context-length. It requires the LLM to to make a travel plan based on a fictional city.
  threshold: 0.6
  vars: 
    name: 010_trip_plan
    difficulties:
      context-length: 3
      reasoning-depth: 4
      instruction-compliance: 1
    prompt: file://010_trip_plan_prompt.txt
  assert:
    - type: icontains	
      value: "Coral Isle"
      weight: 1
    - type: icontains	
      value: "$45"
      weight: 1
    - type: icontains	
      value: "Mango Chili Popsicles"
      weight: 1
    - type: icontains	
      value: "$7"
      weight: 1
    - type: icontains	
      value: "English"
      weight: 1
    - type: icontains	
      value: "Koshi"
      weight: 1