- description: This test mainly focuses on reasoning-depth and context-length. It requires the LLM to to make a travel plan based on a fictional city.
  threshold: 0.6
  vars: 
    name: 010_trip_plan
    difficulties:
      context-length: 3
      reasoning-depth: 4
      instruction-compliance: 1
    prompt: file://testcases/010_trip_plan_prompt.txt
  assert:
    - type: javascript
      value: |
        var lowerCaseStr = output.toLowerCase();
        if (lowerCaseStr.length < 500){
          return false;
        }
        var score = 0;
        if (lowerCaseStr.includes("budget") || lowerCaseStr.includes("cost")){
          score += 0.3;
        }
        if (lowerCaseStr.includes("day 3") || lowerCaseStr.includes("day three")){
          score += 0.3
          if (lowerCaseStr.includes("day 4") || lowerCaseStr.includes("day four")){
            score -= 0.1
          }
          if (lowerCaseStr.includes("day 5") || lowerCaseStr.includes("day five")){
            score -= 0.1
          }
        }
        if (lowerCaseStr.includes("2 people") || lowerCaseStr.includes("two people") || lowerCaseStr.includes("a couple") || lowerCaseStr.includes("per person") || lowerCaseStr.includes("for two")){
          score += 0.4
        }

        return score;
      weight: 1  