- description: This test mainly focuses on reasoning-depth and reasoning-depth. It requires the LLM to analyze the pattern of the log and learn the commands to update the setup.
  threshold: 1
  vars: 
    name: 012_linux_terminal
    difficulties:
      context-length: 3
      reasoning-depth: 3
      instruction-compliance: 1
    prompt: file://testcases/012_linux_terminal_prompt.txt
  assert:
    - type: contains-all
      value:
        - 'git pull'
        - 'git submodule update'
        - 'make install-app'
      weight: 7
    - type: contains-all
      value:
        - 'git pull'
        - 'git submodule update'
      weight: 2
    - type: contains-all
      value:
        - 'git pull'
      weight: 1