- description: This test mainly focuses on context-length and instruction-compliance. It requires the LLM to avoid the pitfall that the user sets and refuse to answer user's question.
  threshold: 1
  vars: 
    name: 014_find_target_files
    difficulties:
      context-length: 2
      reasoning-depth: 4
      instruction-compliance: 1
    prompt: file://testcases/014_find_target_files_prompt.txt
  assert:
    - type: javascript
      value: file://testcases/014_find_target_files_assert.js
      weight: 1  