- description: 
  threshold: 0.6
  vars: 
    name: 016_balls
    difficulties:
      context-length: 1
      reasoning-depth: 2
      instruction-compliance: 1
    prompt: file://testcases/016_balls_prompt.txt
  assert:
    - type: icontains-any
      value: 
        - "in the bedroom"
        - "on the bedroom"
      weight: 1