import c001_requirement_check_config from '@testcases/001_requirement_check_config.yaml?raw';
import p001_requirement_check_prompt from '@testcases/001_requirement_check_prompt.txt?raw';
import c002_code_completion_config from '@testcases/002_code_completion_config.yaml?raw';
import p002_code_completion_prompt from '@testcases/002_code_completion_prompt.txt?raw';
import c003_context_code_fix_config from '@testcases/003_context_code_fix_config.yaml?raw';
import p003_context_code_fix_prompt from '@testcases/003_context_code_fix_prompt.txt?raw';
import c004_sed_command_config from '@testcases/004_sed_command_config.yaml?raw';
import p004_sed_command_prompt from '@testcases/004_sed_command_prompt.txt?raw';
import a005_babel_elements_assert from '@testcases/005_babel_elements_assert.js?raw';
import c005_babel_elements_config from '@testcases/005_babel_elements_config.yaml?raw';
import p005_babel_elements_prompt from '@testcases/005_babel_elements_prompt.txt?raw';
import c006_reading_comprehension_config from '@testcases/006_reading_comprehension_config.yaml?raw';
import p006_reading_comprehension_prompt from '@testcases/006_reading_comprehension_prompt.txt?raw';
import c007_find_ball_config from '@testcases/007_find_ball_config.yaml?raw';
import p007_find_ball_prompt from '@testcases/007_find_ball_prompt.txt?raw';
import c008_email_assistant_config from '@testcases/008_email_assistant_config.yaml?raw';
import p008_email_assistant_prompt from '@testcases/008_email_assistant_prompt.txt?raw';
import a009_customer_service_assert from '@testcases/009_customer_service_assert.js?raw';
import c009_customer_service_config from '@testcases/009_customer_service_config.yaml?raw';
import p009_customer_service_prompt from '@testcases/009_customer_service_prompt.txt?raw';
import c010_trip_plan_config from '@testcases/010_trip_plan_config.yaml?raw';
import p010_trip_plan_prompt from '@testcases/010_trip_plan_prompt.txt?raw';
import a011_tool_using_assert from '@testcases/011_tool_using_assert.js?raw';
import c011_tool_using_config from '@testcases/011_tool_using_config.yaml?raw';
import p011_tool_using_prompt from '@testcases/011_tool_using_prompt.txt?raw';
import c012_linux_terminal_config from '@testcases/012_linux_terminal_config.yaml?raw';
import p012_linux_terminal_prompt from '@testcases/012_linux_terminal_prompt.txt?raw';
import c013_conversation_sanitizer_config from '@testcases/013_conversation_sanitizer_config.yaml?raw';
import p013_conversation_sanitizer_prompt from '@testcases/013_conversation_sanitizer_prompt.txt?raw';
import c014_jailbreak_config from '@testcases/014_jailbreak_config.yaml?raw';
import p014_jailbreak_prompt from '@testcases/014_jailbreak_prompt.txt?raw';
import a015_simple_mahjong_assert from '@testcases/015_simple_mahjong_assert.js?raw';
import c015_simple_mahjong_config from '@testcases/015_simple_mahjong_config.yaml?raw';
import p015_simple_mahjong_prompt from '@testcases/015_simple_mahjong_prompt.txt?raw';

const ConfigMap = new Map<string, string>();
const PromptMap = new Map<string, string>();
const AssertMap = new Map<string, string>();

ConfigMap.set('001_requirement_check_config', btoa(unescape(encodeURIComponent(c001_requirement_check_config))));
ConfigMap.set('002_code_completion_config', btoa(unescape(encodeURIComponent(c002_code_completion_config))));
ConfigMap.set('003_context_code_fix_config', btoa(unescape(encodeURIComponent(c003_context_code_fix_config))));
ConfigMap.set('004_sed_command_config', btoa(unescape(encodeURIComponent(c004_sed_command_config))));
ConfigMap.set('005_babel_elements_config', btoa(unescape(encodeURIComponent(c005_babel_elements_config))));
ConfigMap.set('006_reading_comprehension_config', btoa(unescape(encodeURIComponent(c006_reading_comprehension_config))));
ConfigMap.set('007_find_ball_config', btoa(unescape(encodeURIComponent(c007_find_ball_config))));
ConfigMap.set('008_email_assistant_config', btoa(unescape(encodeURIComponent(c008_email_assistant_config))));
ConfigMap.set('009_customer_service_config', btoa(unescape(encodeURIComponent(c009_customer_service_config))));
ConfigMap.set('010_trip_plan_config', btoa(unescape(encodeURIComponent(c010_trip_plan_config))));
ConfigMap.set('011_tool_using_config', btoa(unescape(encodeURIComponent(c011_tool_using_config))));
ConfigMap.set('012_linux_terminal_config', btoa(unescape(encodeURIComponent(c012_linux_terminal_config))));
ConfigMap.set('013_conversation_sanitizer_config', btoa(unescape(encodeURIComponent(c013_conversation_sanitizer_config))));
ConfigMap.set('014_jailbreak_config', btoa(unescape(encodeURIComponent(c014_jailbreak_config))));
ConfigMap.set('015_simple_mahjong_config', btoa(unescape(encodeURIComponent(c015_simple_mahjong_config))));

PromptMap.set('001_requirement_check_prompt', btoa(unescape(encodeURIComponent(p001_requirement_check_prompt))));
PromptMap.set('002_code_completion_prompt', btoa(unescape(encodeURIComponent(p002_code_completion_prompt))));
PromptMap.set('003_context_code_fix_prompt', btoa(unescape(encodeURIComponent(p003_context_code_fix_prompt))));
PromptMap.set('004_sed_command_prompt', btoa(unescape(encodeURIComponent(p004_sed_command_prompt))));
PromptMap.set('005_babel_elements_prompt', btoa(unescape(encodeURIComponent(p005_babel_elements_prompt))));
PromptMap.set('006_reading_comprehension_prompt', btoa(unescape(encodeURIComponent(p006_reading_comprehension_prompt))));
PromptMap.set('007_find_ball_prompt', btoa(unescape(encodeURIComponent(p007_find_ball_prompt))));
PromptMap.set('008_email_assistant_prompt', btoa(unescape(encodeURIComponent(p008_email_assistant_prompt))));
PromptMap.set('009_customer_service_prompt', btoa(unescape(encodeURIComponent(p009_customer_service_prompt))));
PromptMap.set('010_trip_plan_prompt', btoa(unescape(encodeURIComponent(p010_trip_plan_prompt))));
PromptMap.set('011_tool_using_prompt', btoa(unescape(encodeURIComponent(p011_tool_using_prompt))));
PromptMap.set('012_linux_terminal_prompt', btoa(unescape(encodeURIComponent(p012_linux_terminal_prompt))));
PromptMap.set('013_conversation_sanitizer_prompt', btoa(unescape(encodeURIComponent(p013_conversation_sanitizer_prompt))));
PromptMap.set('014_jailbreak_prompt', btoa(unescape(encodeURIComponent(p014_jailbreak_prompt))));
PromptMap.set('015_simple_mahjong_prompt', btoa(unescape(encodeURIComponent(p015_simple_mahjong_prompt))));

AssertMap.set('005_babel_elements_assert', btoa(unescape(encodeURIComponent(a005_babel_elements_assert))));
AssertMap.set('009_customer_service_assert', btoa(unescape(encodeURIComponent(a009_customer_service_assert))));
AssertMap.set('011_tool_using_assert', btoa(unescape(encodeURIComponent(a011_tool_using_assert))));
AssertMap.set('015_simple_mahjong_assert', btoa(unescape(encodeURIComponent(a015_simple_mahjong_assert))));

export { ConfigMap, PromptMap, AssertMap };
